### ISSUE TITLE
nanopool problem

### ISSUE THREAD

**Issue by jfcg** [robvanmieghem/gominer#29]
hi,
i am running as:
gominer -E 2,3 -url 'stratum+tcp://sia-eu1.nanopool.org:7777' -user ...

i am getting the following:
2017/12/18 23:13:27 ERROR Invalid response from stratum: **true**
2017/12/18 23:13:27 ERROR fetching work - No job received from stratum server yet
2017/12/18 23:13:27 Error in connection to stratumserver: read tcp :49638->198.251.88.14:7777: use of closed network connection
2017/12/18 23:13:27 Connecting to sia-eu1.nanopool.org:7777
etc.

thx

**Comment by Blaster724** [comment]
I dont think the port is supposed to be :7777 I think it has to be the other port on nanopool. I think it was :9898 or something like that. It's the gatenet port I think

**Comment by jfcg** [comment]
This works:
gominer -E 2,3 -url 'sia-eu1.nanopool.org:9980' -user ... 

There is a problem with stratum code

**Comment by jfcg** [comment]
I could not see my account on nanopool afters ours. 
What is a working commandline?

**Comment by robvanmieghem** [comment]
I'll look in to it this weekend but I suspect the stratum implementation is not compatible

**Comment by robvanmieghem** [comment]
email I sent to nanonpool support:

Hello,

As the author of gominer (github.com/robvanmieghem/gominer) I would like to adapt it to your stratum implementation. Can you send me a description of it since it does not seem to comply with “standard “ stratum ( if that even exists). For example, as the result of a mining.subscribe: {"method":"mining.subscribe","params":["gominer"],"id":1}
you normally get something that contains the extranonce1 like {"id":1,"error":null,"result":[[["mining.notify","0101e73838f106a7"],["mining.set_difficulty","0101e73838f106a72"]],"0101e738",4]} 
In your case, the response is {"jsonrpc":"2.0","id":1,"result":true}
Anyway, a description of your protocol would be handy to make gominer nanopool compliant instead of  a guessing approach.
By the way, on your site, you link to gominer source and binaries of siamining instead of the original one  (github.com/robvanmieghem/gominer).

Best regards,
Rob Van Mieghem

**Comment by robvanmieghem** [comment]
nanonpool answer:
Hello,
we are in the middle of upgrading the SIA backend and adding siamining pool stratum support, so there is no use to support our old connection type.
Instead it would be nice to get your current stratum implementation description to make sure we've got it right.
