### ISSUE TITLE
Is there any WINDOWS build for go miner?

### ISSUE THREAD

**Issue by beyinsi** [robvanmieghem/gominer#5]
windows built of go miner?

**Comment by robvanmieghem** [comment]
Gominer builds perfectly on windows, no problem there. There are indeed no windows binaries released and I have multiple reasons for this:
1) I do not want to be accused of cheating if someone does not find blocks in the expected rate
2) What if my windows build environment is compromised (virus or something else)? I do not want to be responsible for distributing a compromised binary.
3) I do not want my github account to be target of attack to replace the binary with a compromised one.

All code is open source and build instructions are on the main readme but do not expect me to produce binaries as long as no deterministic build system is in place so I can prove that the binary is produced from a specific source.

**Comment by Steve1943** [comment]
So all I have to do is download and install GeMiner.go :
Sounds straightforward - although "Go" is new to me.

However, I'm not helpless - having built and hosted scores of websites (LAMP/cPanel on CENTOS after dev/test on Windows with XAMPP).
Also I have built a few miners under Debian via VirtualBox.  Some worked and others did not - but they all built! 

So:

1) "GO" language
	Find the SDK, download, install and learn to use it with tutorials provided.
	Pretty straightforward, UNTIL problems arose in build process (due to GCC and OpenCL integration issues)

2) Github.com 
	I have no experience in open-source development and did not use Github before.
	So open account, install tools and learn to use, sufficiently to download packages.
	
	Discovered that the build/install process is not handled by Github, which is just a repository manager/version controller.
	So when GoMiner.go failed to build, it was necessary to debug the "Go" build process; then find compatible packages to satisfy dependencies.

3) Windows build system for software originally created under Linux/Unix.
	GoMiner failed to build firstly because a suitable C-compiler was not found or incompatible.  
	And OpenCL was never linked despite all my efforts to date.
	
	The Windows scene is a total mess between 32/64bit versions and most users are totally beyond their depth to resolve the many compatibility issues.
	
	After some study I found MinSys2 which incorporates Pacman.
	Pacman provides basic YUM/APT functions plus a Cygwin based console.
 	Eventually I was able to locate and install GCC and OpenCL for 64bit Windows (via Wingw64).

	Independently, I also installed the Intel SDK for OpenCL (because I would like to explore what is possible with the built-in GPU in my i5-5675C, which presently sits idle).
	But, I was equally unable to get GoMiner to find the Intel API.

4 SUMMARY

I failed to install GoMiner on Windows10(Home).  
Some interesting experience gained, but otherwise nothing much to show for my efforts.  
I hazard that 95%+ of Windows users would have given up long before I did.

Your reasons for not providing executables are entirely understandable.  
Unfortunately, it is quite impractical for AMATEUR users to make/build applications on Windows until much greater progress is made in resolving the 32/64bit transition.
There's just too much to go wrong.

**Comment by robvanmieghem** [comment]
@Steve1943 I understand your frustration and indeed, build instructions for linux are really straightforward. This is an old ticket and I indeed realise that producing a windows might not be easy (it helps if you know how to use gcc on windows) so there are windows binaries available in the releases now ( https://github.com/robvanmieghem/gominer/releases ).

**Comment by robvanmieghem** [comment]
@Steve1943 By the way, I made the windows build using the intel SDK as well, just make sure the opencl folder is on your library path and the include folder is set correctly in the environment as well.

**Comment by robvanmieghem** [comment]
@Steve1943 I will create a new windows binary to drop the stale rate tomorrow, it might be as high as 0.5% on the current binary but the latest source drops it to 0.1
